platform:
  - x86

image: Visual Studio 2015

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" ..
  - cmake --build .
