CMAKE_MINIMUM_REQUIRED(VERSION 3.0)
PROJECT(luahpdf C)

FIND_LIBRARY(hpdfs hpdfs)
FIND_PACKAGE(lua REQUIRED)
FIND_PACKAGE(ZLIB REQUIRED)
FIND_PACKAGE(PNG REQUIRED)

ADD_LIBRARY(luahpdf STATIC hpdf.c)

TARGET_LINK_LIBRARIES(luahpdf PUBLIC ${hpdfs} lua ZLIB::ZLIB PNG::PNG)

TARGET_INCLUDE_DIRECTORIES(luahpdf PUBLIC ${CMAKE_INSTALL_PREFIX}/include)

INSTALL(TARGETS luahpdf EXPORT luahpdf-targets DESTINATION lib)

INSTALL(EXPORT luahpdf-targets FILE luahpdf-config.cmake DESTINATION lib/cmake/luahpdf)
